[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:apache]
command=apache2-foreground
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/apache.err.log
stdout_logfile=/var/log/supervisor/apache.out.log

[program:reverb]
command=php /var/www/html/artisan reverb:start --host=0.0.0.0 --port=9090
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/reverb.err.log
stdout_logfile=/var/log/supervisor/reverb.out.log
