-- 1. MIGRACION
ALTER TABLE personal MODIFY COLUMN rol ENUM("cajero", "planchero", "seguridad") NOT NULL;

-- 2. ASEGURAR PERSONAL
INSERT INTO personal (nombre, rol, sueldo_base, activo)
SELECT "Claudio", "seguridad", 0, 0
WHERE NOT EXISTS (SELECT 1 FROM personal WHERE nombre = "Claudio");

SET @claudio_id = (SELECT id FROM personal WHERE nombre = "Claudio" LIMIT 1);
SET @ricardo_id = (SELECT id FROM personal WHERE nombre = "Ricardo" LIMIT 1);

INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-01", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-02", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-03", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-04", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-05", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-06", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-07", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-08", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-09", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-10", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-11", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-12", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-13", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-14", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-15", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-16", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-17", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-18", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-19", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-20", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-21", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-22", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-23", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-24", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-25", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-26", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-27", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-28", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-01-29", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-30", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-01-31", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-01", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-02", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-03", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-04", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-05", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-06", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-07", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-08", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-09", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-10", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-11", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-12", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-13", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-14", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-15", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-16", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-17", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-18", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-19", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-20", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-21", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-22", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-23", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-24", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-25", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-02-26", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-27", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-02-28", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-01", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-02", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-03", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-04", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-05", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-06", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-07", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-08", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-09", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-10", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-11", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-12", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-13", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-14", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-15", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-16", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-17", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-18", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-19", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-20", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-21", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-22", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-23", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-24", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-25", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-26", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-27", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-28", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-29", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-03-30", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-03-31", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-01", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-02", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-03", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-04", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-05", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-06", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-07", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-08", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-09", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-10", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-11", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-12", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-13", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-14", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-15", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-16", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-17", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-18", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-19", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-20", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-21", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-22", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-23", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-24", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-25", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-26", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-04-27", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-28", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-29", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-04-30", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-01", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-02", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-03", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-04", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-05", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-06", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-07", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-08", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-09", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-10", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-11", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-12", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-13", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-14", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-15", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-16", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-17", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-18", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-19", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-20", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-21", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-22", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-23", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-24", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-25", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-26", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-27", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-28", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-05-29", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-30", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-05-31", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-01", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-02", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-03", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-04", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-05", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-06", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-07", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-08", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-09", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-10", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-11", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-12", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-13", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-14", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-15", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-16", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-17", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-18", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-19", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-20", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-21", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-22", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-23", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-24", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-25", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-06-26", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-27", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-28", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-29", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-06-30", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-01", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-02", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-03", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-04", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-05", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-06", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-07", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-08", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-09", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-10", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-11", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-12", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-13", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-14", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-15", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-16", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-17", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-18", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-19", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-20", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-21", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-22", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-23", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-24", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-25", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-26", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-27", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-07-28", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-29", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-30", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-07-31", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-01", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-02", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-03", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-04", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-05", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-06", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-07", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-08", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-09", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-10", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-11", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-12", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-13", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-14", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-15", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-16", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-17", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-18", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-19", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-20", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-21", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-22", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-23", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-24", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-25", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-26", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-27", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-28", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-08-29", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-30", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-08-31", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-01", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-02", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-03", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-04", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-05", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-06", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-07", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-08", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-09", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-10", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-11", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-12", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-13", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-14", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-15", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-16", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-17", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-18", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-19", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-20", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-21", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-22", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-23", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-24", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-25", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-09-26", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-27", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-28", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-29", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-09-30", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-01", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-02", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-03", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-04", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-05", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-06", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-07", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-08", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-09", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-10", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-11", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-12", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-13", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-14", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-15", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-16", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-17", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-18", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-19", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-20", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-21", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-22", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-23", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-24", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-25", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-26", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-27", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-10-28", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-29", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-30", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-10-31", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-01", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-02", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-03", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-04", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-05", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-06", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-07", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-08", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-09", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-10", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-11", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-12", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-13", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-14", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-15", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-16", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-17", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-18", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-19", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-20", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-21", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-22", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-23", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-24", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-25", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-26", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-27", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-28", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-11-29", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-11-30", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-01", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-02", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-03", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-04", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-05", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-06", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-07", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-08", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-09", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-10", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-11", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-12", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-13", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-14", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-15", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-16", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-17", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-18", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-19", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-20", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-21", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-22", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-23", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-24", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-25", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-26", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@claudio_id, "2026-12-27", "seguridad"); -- Claudio
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-28", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-29", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-30", "seguridad"); -- Ricardo
INSERT INTO turnos (personal_id, fecha, tipo) VALUES (@ricardo_id, "2026-12-31", "seguridad"); -- Ricardo
